export type WallFormType = {
  blockDensity: number;
  blockHeatConduction: number;
  blockName: string;
  blockThickness: number;
  concreteHeatConduction: number;
  concreteThickness: number;
  hasSecondInsulation: boolean;
  insulationDensity: string;
  insulationHeatConduction: number;
  insulationName: string;
  insulationThickness: number;
  isBlockSp: boolean;
  isConcreteSp: boolean;
  isInsulationSp: boolean;
  isSecondInsulationSp: boolean;
  secondInsulationDensity: string;
  secondInsulationHeatConduction: number;
  secondInsulationName: string;
  secondInsulationThickness: number;
};
