export type WallFormType = {
  blockDensity: number;
  blockHeatConduction: number;
  blockName: string;
  blockThickness: number;
  concreteHeatConduction: number;
  concreteThickness: number;
  hasSecondInsulation: boolean;
  insulationDensity: string;
  insulationHeatConduction: number;
  insulationName: string;
  insulationThickness: number;
  isblockSp: boolean;
  isconcreteSp: boolean;
  isinsulationSp: boolean;
  issecondInsulationSp: boolean;
  secondInsulationDensity: string;
  secondInsulationHeatConduction: number;
  secondInsulationName: string;
  secondInsulationThickness: number;
};
